// Fetches the console's two third-party assets and writes them into the
// Worker as string modules, so the page depends on no domain but its own.
//
//   node cf/scripts/vendor.mjs
//
// htmx is checked against the hash cdnjs publishes for the release before it
// is written. The font is the latin subset Google serves for Geist Mono, one
// variable-weight file covering 400–600; Geist is under the SIL OFL 1.1, and
// the licence sits next to it. Re-run to bump either; the served paths carry
// the version, so a new file gets a new name and the old one falls out of
// caches on its own.
import { writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HTMX_VERSION = "1.9.12";
const FONT_VERSION = "v6";
const out = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "vendor");

const htmxUrl = `https://cdnjs.cloudflare.com/ajax/libs/htmx/${HTMX_VERSION}/htmx.min.js`;
const htmx = await (await fetch(htmxUrl)).text();
const sri = (await (await fetch(`https://api.cdnjs.com/libraries/htmx/${HTMX_VERSION}?fields=sri`)).json()).sri["htmx.min.js"];
const sha512 = "sha512-" + createHash("sha512").update(htmx).digest("base64");
if (sri !== sha512) throw new Error(`htmx ${HTMX_VERSION}: cdnjs says ${sri}, download hashes to ${sha512}`);

const ua = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36";
const css = await (await fetch("https://fonts.googleapis.com/css2?family=Geist+Mono:wght@400;500;600&display=swap", { headers: { "user-agent": ua } })).text();
const at = css.indexOf("/* latin */"); const latin = css.slice(at, css.indexOf("}", at) + 1);
const range = /unicode-range: ([^;]+);/.exec(latin)[1];
const urls = new Set([...latin.matchAll(/src: url\(([^)]+)\)/g)].map((m) => m[1]));
if (urls.size !== 1) throw new Error(`expected one variable-weight file for the latin subset, got ${urls.size}`);
const woff2 = Buffer.from(await (await fetch([...urls][0])).arrayBuffer());
if (woff2.subarray(0, 4).toString() !== "wOF2") throw new Error("not a woff2");
const licence = await (await fetch("https://raw.githubusercontent.com/vercel/geist-font/main/LICENSE.txt")).text();

const header = (what) => `// Generated by cf/scripts/vendor.mjs — ${what}. Do not edit by hand.\n`;
writeFileSync(join(out, "htmx.ts"), header(`htmx ${HTMX_VERSION} from ${htmxUrl}`) +
  `export const HTMX_VERSION = ${JSON.stringify(HTMX_VERSION)};\n` +
  `export const HTMX_SHA512 = ${JSON.stringify(sha512)};\n` +
  `export const HTMX_JS = ${JSON.stringify(htmx)};\n`);
writeFileSync(join(out, "geist-mono.ts"), header(`Geist Mono ${FONT_VERSION}, latin subset, variable weight; SIL OFL 1.1, see LICENSE-geist.txt`) +
  `export const GEIST_MONO_VERSION = ${JSON.stringify(FONT_VERSION)};\n` +
  `export const GEIST_MONO_UNICODE_RANGE = ${JSON.stringify(range)};\n` +
  `export const GEIST_MONO_WOFF2_BASE64 = ${JSON.stringify(woff2.toString("base64"))};\n`);
writeFileSync(join(out, "LICENSE-geist.txt"), licence);
console.log(`htmx ${HTMX_VERSION} ${htmx.length} chars (${sha512}); Geist Mono ${FONT_VERSION} ${woff2.length} bytes; ${range.split(",").length} ranges`);
